[build]
  command = "npm run build"
  publish="https://github.com/Upskilling-eg/Food-react-admin-app/build"
  base = "https://github.com/Upskilling-eg/Food-react-admin-app"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200